# -*- mode: python -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['/Users/cjshaw/Documents/Projects/CLIx/qbank-lite'],
             binaries=None,
             datas=[],
             hiddenimports=['dlkit',
                            'dlkit.filesystem',
                            'dlkit.filesystem.osid.managers',
                            'dlkit.filesystem.osid.sessions',
                            'dlkit.filesystem.osid.objects',
                            'dlkit.filesystem.repository.managers',
                            'dlkit.filesystem.repository.sessions',
                            'dlkit.filesystem.repository.objects',
                            'dlkit.mongo',
                            'dlkit.mongo.assessment.managers',
                            'dlkit.mongo.assessment.sessions',
                            'dlkit.mongo.assessment.objects',
                            'dlkit.mongo.logging_.managers',
                            'dlkit.mongo.logging_.sessions',
                            'dlkit.mongo.logging_.objects',
                            'dlkit.mongo.repository.managers',
                            'dlkit.mongo.repository.sessions',
                            'dlkit.mongo.repository.objects',
                            'dlkit.services',
                            'dlkit.services.assessment',
                            'dlkit.services.logging_',
                            'dlkit.services.repository',
                            'records',
                            'records.assessment',
                            'records.assessment.basic',
                            'records.assessment.basic.assessment_records',
                            'records.assessment.basic.base_records',
                            'records.assessment.basic.file_answer_records',
                            'records.assessment.basic.multi_choice_records',
                            'records.assessment.basic.simple_records',
                            'records.assessment.qti',
                            'records.assessment.qti.basic',
                            'records.osid',
                            'records.osid.base_records'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='main',
          debug=False,
          strip=False,
          upx=True,
          console=False )
app = BUNDLE(exe,
             name='main.app',
             icon=None,
             bundle_identifier=None)
